CREATE TABLE project_files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    uploaded_by   BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    original_name VARCHAR(255) NOT NULL,
    stored_name   VARCHAR(255) NOT NULL,
    content_type  VARCHAR(150) NOT NULL,
    size_bytes    BIGINT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_project_files_project ON project_files (project_id, created_at DESC);
