-- Pending invitations addressed to an email that has no TeamFlow account yet. Once that email
-- registers, the row is converted into a workspace_members(INVITED) entry and deleted.
CREATE TABLE workspace_invitations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    email        VARCHAR(255) NOT NULL,
    role         VARCHAR(20) NOT NULL,
    invited_by   BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uq_workspace_invitation UNIQUE (workspace_id, email)
);

CREATE INDEX idx_workspace_invitations_email ON workspace_invitations (email);
